# Generated by Django 3.2.18 on 2023-04-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
